### PR TITLE
Fix CI and do cleanup

### PR DESCRIPTION
**Pull request by tobias-urdin**
This gets the CI working again on Ubuntu 22.04 (Jammy) with Python 3.10, we are not testing with Python 3.9 right now because we need the Ceph jobs to be skipped for that because the python3-rados package is required for that.

This reverts commit 867f7aee58e0b429fcd3a91cfb5197a6f417ee11 that was wrong but not caught due to no CI.

This moves away from PBR to just using setuptools and adds a job to verify building, also removes the support for Python 3.6 and 3.7 in setup.cfg which means the minimum supported version will be Python 3.8 even though that is not tested as of now.

### CODE REVIEW

**Comment by felixonmars** [comment]
It seems that the CI fails after merging. Any ideas?

image

**Comment by tobias-urdin** [comment]
I think that's because github actions needs write permissions for packages to upload the CI docker image, should be somewhere in the settings

**Comment by tobias-urdin** [comment]
@jd can you go to Settings -> GitHub Actions -> Workflow permissions section and verify "Read and write permissions" is checked

**Comment by jd** [comment]
CleanShot 2024-01-29 at 12 22 47@2x
It is, I did not change anything.

**Comment by tobias-urdin** [comment]
> CleanShot 2024-01-29 at 12 22 47@2x It is, I did not change anything.

not sure what permission is needed, but the push from the CI job to packages is failing https://github.com/jd/pifpaf/actions/runs/7696530204/job/20971565237

**Pull request merged**
