### PR TITLE
Allow the RedisDriver to launch a Redis Cluster.

### PR DESCRIPTION
**Pull request by maeln**
The current `RedisDriver` didn't have the ability to launch a 3 node HA Redis Cluster. 
This PR ain to add this functionality. 
Note that Sentinel and Cluster are exclusive. This is reflected in the code.

### CODE REVIEW

**Comment by zzzeek** [comment]
hey folks, dogpile.cache / sqlalchemy here, is pifpaf still being maintained?   this is a pretty simple PR and it's kind of blocking us on merging a new feature with tests.   if pifpaf is no longer maintained we'd need to start devising alternatives

**Comment by jd** [comment]
@zzzeek it's slightly maintained, I think the main issue here is that the CI did not run and I'm not even sure CI is still working TBH.

**Comment by zzzeek** [comment]
@jd you're here!  thanks so much, I know all about "slightly maintained" and that's fine :)    yah the PR here looks a little bigger than I thought

**Comment by maeln** [comment]
I have no time to work on this sadly.

**Pull request closed without merging**
