### PR TITLE
Add Ceph Nautilus and later support

### PR DESCRIPTION
**Pull request by tobias-urdin**
We need to make sure the new msgrv2 protocol
is enabled or a HEATLH_WARN will be issued.

### CODE REVIEW

**Comment by tobias-urdin** [comment]
@jd need this and a release to bump ceph usage with pifpaf :)

**Comment by tobias-urdin** [comment]
Please hold off with this until I've got it working with Gnocchi :)

**Comment by tobias-urdin** [comment]
Have this working locally on a test machine, but might be good to wait with this until Gnocchi CI is green and I can use a newer Ceph version there.

**Comment by jd** [comment]
Let me know. The CI is also broken for pifpaf which is another issue :(

**Comment by tobias-urdin** [comment]
@jd can you merge this and tag a new release, thanks!

**Comment by tobias-urdin** [comment]
@jd need release to pypi too i think

**Comment by jd** [comment]
done

**Pull request merged**
