### PR TITLE
Fix Travis CI and migrate to stestr 

### PR DESCRIPTION
**Pull request by felixonmars**
- [x] ubuntu bionic fails to install npm
- [x] ubuntu focal has no mysql-server-5.7
- [x] migrate from testrepository to stestr
- [x] aodh tests hang
- [x] ceph tests hang https://github.com/jd/pifpaf/issues/148

### CODE REVIEW

**Comment by tobias-urdin** [comment]
Just a heads up that I'm working on fixing SQLALchemy 1.4 for Gnocchi here https://github.com/gnocchixyz/gnocchi/pull/1147

**Comment by tobias-urdin** [comment]
This seems pretty stale, @felixonmars will you be able to work on this again? I will see if I can get some time to get it working then we can hopefully merge the pending PRs.

**Comment by felixonmars** [comment]
> This seems pretty stale, @felixonmars will you be able to work on this again? I will see if I can get some time to get it working then we can hopefully merge the pending PRs.

It seems Travis wasn't triggered at all now. Probably this needs to be combined with the effort to migrate to GitHub CI instead.

**Comment by jkawamoto** [comment]
@felixonmars I could run tests on Travis https://app.travis-ci.com/github/jkawamoto/pifpaf/builds/254811785. Perhaps, they were out of service when you ran last time, and hopefully it’s working now.

I fixed the hang of ceph tests and opened a PR https://github.com/felixonmars/pifpaf/pull/1.

pep8 is still failing in the above PR, but I think it’d be better to fix styling issues in a separate PR or after rebasing this branch onto master.

**Comment by jkawamoto** [comment]
I think ceph tests don’t hang now. Can we merge this PR?

If we need to migrate to GitHub Actions, https://github.com/felixonmars/pifpaf/pull/2 implements it.

**Comment by felixonmars** [comment]
Thanks a lot!

And sorry for the very long delay.

**Pull request merged**
